Repository github/contributors, pull requests merged in 2023-10, with the labels that each got.

#22 fix: shorten commit_urls by using links in markdown
  README.md
  markdown.py
  test_markdown.py
Labels: enhancement

#24 Improve docstrings for functions to be more complete
  contributor_stats.py
  contributors.py
Labels: documentation

#26 Add sponsors config, output, and tests
  .env-example
  .pylintrc
  README.md
  contributor_stats.py
  contributors.py
  env.py
  markdown.py
  requirements.txt
  test_contributor_stats.py
  test_contributors.py
  test_env.py
  test_markdown.py
Labels: enhancement

#27 Fix documentation for the example workflow file
  README.md
Labels: documentation

#28 Catch divide by zero case for no new contributors
  markdown.py
Labels: bug

#29 Correct Workflow file env variables
  README.md
Labels: documentation

#32 Fix workflow job name
  README.md
Labels: documentation

#31 fix url for release changesets
  .github/release-drafter.yml
Labels: infrastructure

#33 Catch exception for empty repositories
  contributors.py
Labels: bug

#36 Allow repository list input
  README.md
  contributors.py
  env.py
  test_contributors.py
  test_env.py
Labels: enhancement

#41 README: fix typo.
  README.md
Labels: documentation

#43 Continue if repo contributors are empty
  contributors.py
Labels: bug
