Repository github/contributors, pull requests merged in 2024-05, with the labels that each got.

#103 chore: add OSSF scorecard github action and README badge
  .github/workflows/auto-labeler.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yaml
  README.md
Labels: maintenance

#109 chore: group dependabot dependency updates for minor/patch updates
  .github/dependabot.yml
  .github/workflows/contributors_report.yaml
  .github/workflows/docker-ci.yml
  .github/workflows/major-version-updater.yml
  .github/workflows/pr-title.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .github/workflows/scorecard.yml
  .github/workflows/super-linter.yaml
Labels: maintenance, release

#115 feat: json output
  .gitignore
  contributors.py
  json_writer.py
  test_json_writer.py
Labels: feature

#122 ci: release when a new feature hits main
  .github/workflows/release.yml
Labels: automation

#123 chore: remove pull_request target if we already have pull_request_target
  .github/workflows/auto-labeler.yml
  .github/workflows/release.yml
Labels: maintenance

#124 ci: Add Jeff to review new data releases
  .github/pull_request_template.md
Labels: automation
